// This file is generated by npm run build:icons

export type AllIconTypes =
  | 'icons/chip-logo'
  | 'icons/facebook-icon'
  | 'icons/handset'
  | 'icons/instagram-icon'
  | 'icons/login-icon'
  | 'icons/smartphone'
  | 'icons/twitter-icon'
  | 'icons/youtube-icon';
