// This file is generated by npm run build:icons

export type IconType =
  | 'icons/chip-logo'
  | 'icons/exchange-arrows'
  | 'icons/exchange-history-arrow'
  | 'icons/facebook-icon'
  | 'icons/handset'
  | 'icons/instagram-icon'
  | 'icons/login-icon'
  | 'icons/selectinput-arrows'
  | 'icons/selectinput-checkmark'
  | 'icons/smartphone'
  | 'icons/twitter-icon'
  | 'icons/youtube-icon';
